# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42aab6653d1f664aa7b064f0dfefeae2ed7a78606099d30f9214a2e18d58699ef7345cc2332402351fc994858a9af38ee29b8e8812bd62c83ad87c22b1792393

test:
  secret_key_base: 7cf82d98349573cd7ee60011630498f1dc1a2674e8955d71c03cea884ae5512e0a4cdbd5cf496c4e5630323c8d01937408809d7f080351e83775f21c4e59c615

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
